# config/packages/liip_imagine.yaml
liip_imagine:
    driver: gd
    filter_sets:
        resized_image:
            quality: 75
            filters:
                thumbnail: { size: [800, 600], mode: outbound }


