vich_uploader:
    db_driver: orm
    mappings:
        accommodations:
            upload_destination: '%kernel.project_dir%/public/uploads/accommodations'
            uri_prefix: '/uploads/accommodations'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        activities:
            upload_destination: '%kernel.project_dir%/public/uploads/activities'
            uri_prefix: '/uploads/activities'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

