vich_uploader:
    db_driver: orm # Spécifiez le type de base de données utilisé (orm pour Doctrine)
    mappings:
        accommodation:
            uri_prefix: /uploads/accommodations
            upload_destination: '%kernel.project_dir%/public/uploads/accommodations'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true

        activities:
            uri_prefix: /uploads/activities
            upload_destination: '%kernel.project_dir%/public/uploads/activities'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true

